### ISSUE TITLE
Race condition on sidebar settings to threads

### ISSUE THREAD

**Issue by bsian03** [Vap0r1ze/DaveDashboard#9]
Already diagnosing - seems to happen on chromium browsers, unable to reproduce on firefox

At setTimeout, Firefox: 
![image](https://user-images.githubusercontent.com/24302436/78041532-b80eeb80-7368-11ea-9491-d5d4f020caac.png)

Also at setTimeout, Chrome: 
![image](https://user-images.githubusercontent.com/24302436/78041639-db399b00-7368-11ea-9401-7e534c1c0e4e.png) - Issue is the conditional still thinks that it's still on the settings page, and therefore invokes itself to go back a second time, even though by the time the breakpoint reaches the function, it's already on the previous page

I'm opening this so this doesn't get lost

**Comment by bsian03** [comment]
@Vap0r1ze Was there a reason why setTimeout was added? 
![image](https://user-images.githubusercontent.com/24302436/78048279-6454d000-7371-11ea-8cc6-a520658ac498.png)

**Comment by Vap0r1ze** [comment]
@bsian03 what file is that

**Comment by Vap0r1ze** [comment]
Oh, I see, the timeout is there so that I could check the route after the `.go(-1)` took effect. I wanted a really specific functionality for the settings function but this was my first Vue project ever so there are many better ways to go about that.

**Comment by bsian03** [comment]
Alright, I'm assuming you're ok with removing the whole of `setTimeout()` then?

**Comment by Vap0r1ze** [comment]
yea go ahead
